### ISSUE TITLE
Web: naming the files?

### ISSUE THREAD

**Issue by danwdart** [dadi/docs#114]
Given that there were no pre-determined files when I used `npm install`, I was not shown what the directory structure and file structure for pages looked like - the locations, JSON and template file structure were not explained in the docs.

**Comment by jimlambie** [comment]
@danwdart looks like we're missing a section similar to this: https://docs.dadi.cloud/api/4.3#application-anatomy

Feel free to submit a PR

**Comment by danwdart** [comment]
OK cool. I think it ought to have an explanation of the page json files too, regardless of the template manager you use.
