### ISSUE TITLE
The URL for the media upload is /media/upload, not /media

### ISSUE THREAD

**Issue by danwdart** [dadi/docs#116]
In the API code, to upload media, you POST to `/media/upload` and `/media/bucketName/upload`, is it meant to be that rather than POSTing to `/media` and `/media/bucketName` as the doc suggests?

**Comment by jimlambie** [comment]
Closed via https://github.com/dadi/docs/commit/160a525e0508f89349fbda20a94d1e6bab03de7a

**Comment by danwdart** [comment]
Great thank you
