### ISSUE TITLE
Make examples usable

### ISSUE THREAD

**Issue by josephdenne** [dadi/docs#12]
It would be a nice touch for our examples to be usable.

For example, on this page:
http://docs.dadi.tech/cdn/concepts/saturation/

The `https://cdn.example.com/images/beach.jpg?saturate=2.5` to be linked to a testable instance.

We own `somedomain.tech`, which could be nice for this:

`https://cdn.somedomain.tech/images/beach.jpg?saturate=2.5`

**Comment by jimlambie** [comment]
We thought the API samples should also be testable, so a full stack installed on somedomain would be fantastic
