### ISSUE TITLE
Show Next & Previous links

### ISSUE THREAD

**Issue by jimlambie** [dadi/docs#16]
Some pages have `next` & `previous` properties to provide navigation to sibling pages. Consider adding links to these pages at the top or bottom of the content?

```
{{#if this.previous}}
  Prev: <a href="/{{this.previous.path}}">{{{this.previous.title}}}<a/>
{{/if}}
{{#if this.next}}
  Next: <a href="/{{this.next.path}}">{{{this.next.title}}}<a/>
{{/if}}
```

**Comment by abovebored** [comment]
@jimlambie they seem to not be in a particular order e.g., http://docs.dadi.tech/web/getting-started/installing/:

```
Prev
Geolocate your visitors
Next
Loading external data
```

Rather than, blank and 'configuration.

**Comment by jimlambie** [comment]
We can specify the order we want them in as part of the build stage, I'll see what I can do

**Comment by jimlambie** [comment]
See changes in index.js for sorting example
