### ISSUE TITLE
Filter Event callback

### ISSUE THREAD

**Issue by adamkdean** [dadi/docs#63]
The Filter Events documentation shows the callback as just taking the filterObject e.g. `callback(filterObj)` and not taking an error as first param `callback(null, filterObj)`. Is this incorrect or has this changed with a more recent version of Web? @jimlambie?

https://docs.dadi.tech/#web/filter-events

**Comment by jimlambie** [comment]
@adamkdean Please fix!

**Comment by adamkdean** [comment]
👏 @jimlambie
