### ISSUE TITLE
Redirect old docs.dadi.tech site

### ISSUE THREAD

**Issue by abovedave** [dadi/docs#79]
https://docs.dadi.tech/-> https://docs.dadi.cloud/
https://docs.dadi.tech/api/latest -> https://docs.dadi.cloud/api/latest

etc

**Comment by jimlambie** [comment]
@josephdenne I believe this one needs your assistance? We need to drop the current meta bounce and perhaps implement an htaccess rewrite for docs.dadi.tech*
